### ISSUE TITLE
SSH key selection broken

### ISSUE THREAD

**Issue by maks** [maks/MGit#193]
As reported via a Google Play user review, SSH key selection is broken in 1.5.3 as attempting to navigate into a subfolder causes it to be selected as a private key file instead.

**Comment by SenseException** [comment]
I was trying out the app because I'm looking for a replacement for Pocket Git. This is a very old issue. I would appreciate a fix of this bug, because I don't want to adapt my directory structure nor do I want to have redundancy in files or directories.

I'm not an Android developer. Do you already now the reason for this bug?

**Comment by maks** [comment]
@SenseException yes this is just an issue with how the file selector is being (re)used for selecting the private key. I expect to have time in about a week or so to look into this more, in the meantime I'll tag it as a priority for then.

**Comment by maks** [comment]
Actually this is a UX issue not a bug in selection ui, as you need to add keys to MGit using the "Import Key" toolbar menu item s shown below. Improving the UI is now tracked in #326
![screenshot_1524102767](https://user-images.githubusercontent.com/71999/38966977-3be3e852-43c8-11e8-8345-c45386cdd352.png)
