### ISSUE TITLE
Enforce usage of secure cyphersuites and protocol versions in TLS

### ISSUE THREAD

**Issue by KOLANICH** [maks/MGit#259]
As I understand, it is not enforced for now.

https://github.com/eclipse/jgit/blob/5d64d3d83a60f3663e22786eeed7cec03fe6ed40/org.eclipse.jgit.http.apache/src/org/eclipse/jgit/transport/http/apache/HttpClientConnection.java#L173

As you see, no additional work to disable weak cyphersuites is done and TLS 1.0 is allowed.

Also on Android <=4.4.4 TLS 1.2 is not used by default, you need to enforce it to make it work. Since GH [have dropped](https://github.com/blog/2507-weak-cryptographic-standards-removed) old modes, MGit stopped working on <=4.4.4. To make it work you need to enforce 1.2.

**Comment by kaeptmblaubaer1000** [comment]
This code doesn't belong to MGit, it belongs to Eclipse JGit.
You should report this there.
On the other hand, there may be an API from JGit, I will look for one...

**Comment by maks** [comment]
Yes the connection code is within JGit and unfortunately there is no easy way to get JGIt to use an alternative HTTP client library. There may be a setting to enforce the TLS min version @kaeptmblaubaer1000 please post back here if you find anyhting as I wont have time to look into this fro a while.
*BUT* please not that MGit is currently stuck on an old version of JGit (#26) due to changes in the use of  newer Java class library APIs that JGit began using that are not supported on Android.

**Comment by kaeptmblaubaer1000** [comment]
I'm working on this.
I'll try to enforce TLSv1.0-TLSv1.2.
But it's most probably not the only what you want. So I need more information to completely close this issue.

**Comment by maks** [comment]
@kaeptmblaubaer1000 thats great, feel free to post back here with any questions/comments about what you are doing or even open a work-in-progress PR.

**Comment by kaeptmblaubaer1000** [comment]
Enforcing only TLS is done, see my `patch-2` branch. Creating a PR now.

**Comment by maks** [comment]
For future reference, the best discussion of this issue and potential solutions/workaround seems to be in [this okhttp issue](https://github.com/square/okhttp/issues/2372)
