### ISSUE TITLE
Enable logging about TLS errors back into logcat

### ISSUE THREAD

**Issue by KOLANICH** [maks/MGit#260]
2018-02-23 GitHub [have dropped weak TLS modes](https://github.com/blog/2507-weak-cryptographic-standards-removed) and I (surprisingly, since 4.4.4 supports TLS 1.2) have started getting errors accessing GitHub in any app using TLS libraries shipped with Android (both SGit and ForkHub).
Logcat on sgit (the abandoned one) showed that

<details>

```
W/System.err( 4230): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x5de756f0: Failure in SSL library, usually a protocol error
W/System.err( 4230): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x5b731dbc:0x00000000)
```

I don't know why sslv3 is mentioned, it should he disabled by using ```getInstance("TLS")```
</details>

Since MGit also doesn't work, I expect the same message to be shown in logcat.

**Comment by maks** [comment]
Thank you for reporting this.
If it is the case that this is now happening on Android 4.4.4 (or other versions of the platform) then logging to logcat is definitely *NOT* the right thing to do - this then needs to be surfaced as an UI error message/dialog to the user.

**Comment by KOLANICH** [comment]
It's not crashing. In UI is shown that `cannot open git-upload-pack` in both sgit and mgit. But I guess it should also write into logcat the detailed info.

**Comment by madnight** [comment]
Can confirm this problem, both in mgit and sgit

**Comment by maks** [comment]
I'm sorry about the inconvenience this is causing, unfortunately I didnt see the Githubs annoucement til this issue was filed.
For @Wryhder and others that are being affected by this the work around for now is to use SSH instead of HTTPS as your connection protocol. You can do this even for existing repos by adding a new remote for them - just be sure to have already setup your SSH key in Github and MGit per Githubs instructions [and MGits](https://github.com/maks/MGit/wiki/faq#how-do-i-use-a-ssh-certificate)

**Comment by maks** [comment]
Going to close this in favour of tracking the a fix for the undertying issue of using a modern version of TLS on older Android versions in #259.
