### ISSUE TITLE
Replacing Jgit as backend

### ISSUE THREAD

**Issue by prid** [maks/MGit#330]
Sorry if it is asked before or sounds not practical (I'm not a programmer myself so I don't understand the internals). First of all awesome job for all your effort into making this app, really made working on phone a charm.

Is it possible to migrate from Jgit to the native command line git as the backend? It seems like that Termux successfully builds git for Android into a .deb package.

This would expose more functionality of git, for the command line git is the most complete and up-to-date git?

**Comment by maks** [comment]
Hi thank you for asking the question. 

I assume you are asking because of #26 and #321.

Unfortunately using the git cli exe is not a good solution, actually "shelling out" to any cli by a GUI app is not a good tech solution in general.

The only real alternative to jgit is libgit, which is a C library that provides roughly the same functionality the jgit does. The downsides to using libgit is having to deal with JNI and the NDK. I'm definitely not interested in doing that at the moment and would rather maintain a small patchset on top of jgit to be able to continue using the latest versions of jgit. This would have the possiblity of then getting the patches submitted and merged upstream. 

I will have time to look into this more next week and will assess the procs and cons of  @kaeptmblaubaer1000 approach in #321 vs using a patched version of jgit.

**Comment by DrSensor** [comment]
still very experimental but it worth to check out :)
https://github.com/ethomson/jagged

**Comment by maks** [comment]
@DrSensor thank you pointing to that project, it maybe interesting sometime in the future, but as is now its not really relevant for use in MGit.
