### ISSUE TITLE
Git config user section name is incorrect

### ISSUE THREAD

**Issue by beau-mind** [maks/MGit#450]
After setting name and email, "git commit" crashed. The error report asked me to set name and email of the user. The raw config file had a section `[name]`. After I changed the section name to `[user]`, `git commit` started working fine. 

The problem seems to be in the following line:

https://github.com/maks/MGit/blob/c6ae80ef66cd285912db899a86f4bea985eb7625/app/src/main/java/me/sheimi/sgit/database/models/GitConfig.java#L19

**Comment by kaeptmblaubaer1000** [comment]
Yes it looks like that's the issue. But that you have found it shows me a different thing: you haven't configured global user/email. Otherwise it will only be for a single repo and all others will continue to refuse commits. The fix PR should migrate this invalid config section name to the valid one (that is, fix existing broken configs) and use the correct name then.

**Comment by qorron** [comment]
bug still present in 1.5.10 (current playstore version).
took me quite a while to find the odd [name] section in the raw-config of the repo.
using the config still produces the wrong section name.
