### ISSUE TITLE
Allow to generate keys using Elliptic-curve cryptography

### ISSUE THREAD

**Issue by Backfighter** [maks/MGit#487]
Currently only RSA and DSA keys can be generated. Elliptic-curves would be a nice addition.

**Comment by kb-1000** [comment]
It's not about generating them, it's about using them. MGit uses JGit, which in turn uses JSch for SSH connections and key generation. JSch doesn't support those keys. Newer JGit versions support a different SSH library, but those versions wouldn't work on Android because java.nio.file.Path is not present on older devices.

**Comment by maks** [comment]
closed in favour of #545
