### ISSUE TITLE
Transport exceptions during clone should not send sentry error reports

### ISSUE THREAD

**Issue by maks** [maks/MGit#526]
These are typically due to auth errors, incorrect url's, etc so do not need to generate sentry error reports.

**Comment by kb-1000** [comment]
Does sentry send reports without the user seeing them first or an ability to say no to sending?

**Comment by maks** [comment]
Correct. I removed the option in the error dialog for a user to confirm sending an error report as previously happened when sending via an email.
In regards to reporting crashes the default behaviour is to cache the crash and automatically on restart within the sentry client library.

**Comment by kb-1000** [comment]
I would see a GDPR violation in that.

**Comment by maks** [comment]
In my view [subscection e and f](https://gdpr-info.eu/art-6-gdpr/) would mean that it is not. However since I'm not a lawyer, I'll add a separate issue to address this.

**Comment by l3laze** [comment]
Also not a lawyer, but in `f` it mentions kids, and since children are perfectly capable of using this app (whether or not they are) it is safe to assume that `f` should not be applied to this.


In `e` it mentions public interest, which this is as an open source project but I don't think it would legally get past this rule, and there's no authority unless this is government-sponsored somehow, so `e` does not seem to apply either.


An opt-in for automatic error reporting would likely be a better way to solve this, though it obviously wouldn't be as useful unless most people do so.
