### ISSUE TITLE
cannot pull or clone git repo from gogs server since last MGIT version

### ISSUE THREAD

**Issue by infuzz** [maks/MGit#530]
**Describe the bug**
Since last update of MGIT, I cannot clone or pull form origin. Error is  : <url repo> : cannot open git-upload-pack

**To Reproduce**
0. Select a local repo
1. Go to  menu
2. Select Pull
3. click on origin checkbox

Same when adding a new repo

**Smartphone (please complete the following information):**
 - Device: MI 9
 - OS: Android 10
 - App Version 1.5.7
- GOG Version : 0.9.99.0915

**Additional context**
All clone or pull works with CLI on other servers. Doesn't understand whats happen with GOG and MGIT.
all other repos on github work well with MGIT. So there is probably an imcompatibility between GOGS and the last version of MGIT. Do you have any idea on what is happening ?
As all our repos are privaten I'll set up an open demo repo tomorrow on my GOGS to let you have a try if necessary.

Thank you for all your work !

**Comment by maks** [comment]
Yes if you are able to create a publicly available repo that is showing the same problem, that would be a great help.
And sorry I have no idea what "GOG" is ?

**Comment by kb-1000** [comment]
I would guess you mean https://gogs.io/.
However, please actually post that error instead of just saying "see error", as I don't have or want a Gogs instance on my pc to actually test this. But your Gogs version is definitely outdated (0.9.99.0915 is from 2016). In addition to that, I googled for an instance with that version and found one. Cloning a repository from it worked just fine. It COULD be related to your Android version or other things like the repository URL being no longer valid, but please post that error.

**Comment by infuzz** [comment]
Yes you find the right GOGS, a very goog git server. Sure my version is outdated.... need some time to migrate. The error is one I put in description (wrong place !) ; Error is 

`http://giturl:port/owner/depot : cannot open git-upload-pack`

Does this error make sense for you ?

To set up a public repositary test, I need to change fw rules also. I'll try to install a fully new GOGS on a new server without rules to test.

**Comment by maks** [comment]
@infuzz I can easily reproduce your error now that you included that url.
Its not really gogs specific - its because you are trying to use plain, unsecured http. 
Android apps no longer allow http traffic unless the app specifically white-lists it.
Using http is definitely not recommend and not supported by MGit, please use https instead.

**Comment by infuzz** [comment]
Ok thx you really for your support !

**Comment by kb-1000** [comment]
wait a minute... so this means that even http on localhost is disallowed?

**Comment by maks** [comment]
@kb-1000 yes I believe so, but even if it wasn't, it wouldn't make much difference as there is very limited use in having a http connection to a git remote on localhost, is your Android device running MGit.
