### ISSUE TITLE
Does Mgit (a Git client Android App) send data to a third party?

### ISSUE THREAD

**Issue by olivierg615** [maks/MGit#582]
I just want to be informed.

**Comment by olivierg615** [comment]
Thanks!
I sincerely appreciate your efforts and the fact that you responded so quickly. I wish the best for MGit which will help me with my workflow on smartphone.
I will try it!

**Comment by mrusme** [comment]
I was interested in this topic because F-Droid reported this app for using anti-features, specifically Sentry. It would be cool if there was a way to get rid of this. Subscribing to this ticket in order to get notified when it happened in order to install the app then.
Thank you very much for the efforts of building this!

**Comment by maks** [comment]
@mrusme this was done in https://github.com/maks/MGit/pull/597 and went into release 1.6.1
Unfortunately I missed doing a release tag here for 1.6.1 here on Github, so I guess F-droid will only pick it up when they do a build with the current 1.6.2 release: https://github.com/maks/MGit/releases/tag/v1.6.2
which includes removal of Sentry usage along with other fixes, including the important one to fix deprecated ssh encryuption scheme removal.
