### ISSUE TITLE
MGit Error

### ISSUE THREAD

**Issue by clef-shanty** [maks/MGit#615]
Downloaded 1.6.2. 

It won't let me clone a repository. It won't use the ssh key. I did have it working with a passphrase. But now it won't even ask for a username and password. 

All the app does is create the folder for the clone and then gives me a pop-up that says:

Error occurred 

Clone failed
Operation not permitted

**Comment by maks** [comment]
Thank you for opening this issue.
Could I please ask for some further information:
* what git service are you using for the remote repo: Github, other provider or self-hosted?
* were you successfully cloning the same repo with MGit prior to updating to 1.6.2?
* what type of ssh key are you using?
* how did you create the ssh key? If you used MGit to create it, which version of MGit did you use?
* what location on your android device did you select for the local repo root folder?
* are you able to successfully clone a public repo (eg. this one) from Github to that location using SSH, if not does it work with HTTPS?
* if you are given the option of sending a error report in MGit via email please do so

**Comment by yuttai** [comment]
The git repository I used was fine previously, but I recieved "Error occurred" when I tried to open it today... I tried to clone this repository, and then got the same error as clef-shanty.
![Screenshot_20220330-105653_MGit.jpg](https://user-images.githubusercontent.com/15096557/160742080-e17ac2b0-b04d-4d19-9874-7818c918e6b6.jpg)
![Screenshot_20220330-105702_MGit.jpg](https://user-images.githubusercontent.com/15096557/160742096-ee7c5737-5722-4459-a8a1-4da38af5c208.jpg)
- The git server is set by "git.exe daemon". The server didn't show any connection message after I clone.
- I could pull and clone successfully previously. 
- No ssh with git protocol.
- No ssh with git protocol.
- The local repo root folder is in "/storage/emulated/0/git"
![Screenshot_20220330-110902_MGit.jpg](https://user-images.githubusercontent.com/15096557/160743868-490cf92d-a733-4c12-95bc-b0f20070561c.jpg)
- I didn't try, but this happens with git protocol, so I guess this is not an SSH problem.
- I didn't given the option of sending a error report in MGit via email.

**Comment by yuttai** [comment]
The screen capture of the server IP and "git.exe daemon" didn't receive any connection message as below.
![螢幕擷取畫面 2022-03-30 111816](https://user-images.githubusercontent.com/15096557/160744662-5ccd2d7b-bf6d-4c10-aecf-1d48ccf53717.png)

**Comment by maks** [comment]
@yuttai  Thank you for extra information.
I'll need to look into this more, as I can't think why the changes in the latest version o MGit would have affected your ability to clone using the git protocol.

**Comment by clef-shanty** [comment]
So I am using github. I used another app to see if I could clone with it, and it worked. I am having to use https and a passphrase because ssh does not seem to be working on Android correctly, or at least it no longer works with Mgit. I've tried to use RSA at 4086 and it still doesn't like the ssh key that Mgit generates.

Mgit used to work fine up until a couple of weeks ago. Now it is always an error.

**Comment by clef-shanty** [comment]
See attached screenshot of error message.

**Comment by yuttai** [comment]
Just curious. What another app you tried to clone? I didn't find other Android git client which is usable...

Best regards,
Tai, Yu-Tsung (戴淯琮)
github.com/yuttai<http://github.com/yuttai>
orcid.org/0000-0002-0298-1362<http://orcid.org/0000-0002-0298-1362>


-------- 原始訊息 --------
自： clef-shanty ***@***.***>
日期： 2022/3/31 03:50 (GMT+08:00)
至： maks/MGit ***@***.***>
副本： "戴淯琮 (Yu-Tsung Tai)" ***@***.***>, Mention ***@***.***>
主旨： Re: [maks/MGit] MGit Error (Issue #615)


So I am using github. I used another app to see if I could clone with it, and it worked. I am having to use https and a passphrase because ssh does not seem to be working on Android correctly, or at least it no longer works with Mgit. I've tried to use RSA at 4086 and it still doesn't like the ssh key that Mgit generates.

Mgit used to work fine up until a couple of weeks ago. Now it is always an error.

**Comment by ciwchris** [comment]
Same issue. Changing the root folder like @Navirl mentioned also works for me.

**Comment by maks** [comment]
Ah that makes sense, thank you both for pointing that out - I missed the relevance of the root path that @yuttai posted.
I expect this will be due to the new [security/privacy restrictions being imposed with the new "scoped storage" model](https://developer.android.com/about/versions/11/privacy/storage), now that MGit targets API31. 

There is already an issue: #465  for tracking these Android storage issues, so I'll close this as a duplicate but welcome peoples comments there on how they use MGit and how MGit could best address this going forward.
