### ISSUE TITLE
Unable to pull private repositories on my device, prompts Not Authorized

### ISSUE THREAD

**Issue by KujouShiori** [maks/MGit#729]
Hello, I used this tool for the first time, I need to go out for a long time due to work reasons, during which I can't touch the computer, I'm trying to use my Android phone to pull and edit my Github repository, this repository holds some important data so I make it private, I tried to use mgit to pull, but the APP prompts Not Authorized, it still can't be solved after entering the correct account name/email and password, and it still can't be solved after changing the network, Please help me

你好，我第一次使用这个工具，由于工作原因，我需要长时间外出，在此期间我不能接触电脑，我试图用我的安卓手机拉取和编辑我的 Github 仓库，这个仓库保存了一些重要数据，所以我将它设为私有，我试图使用 mgit 拉取，但 APP 提示未授权，输入正确的账户名/电子邮件和密码后仍无法解决，更改网络后仍无法解决，请帮助我。

**Comment by maks** [comment]
This sounds like you are trying to use your Github password to clone a private repo which is *NOT* supported by GitHub. Instead you need to create and use a personal token instead of your password, [see the FAQ entry here](https://github.com/maks/MGit/wiki/faq#how-can-i-login-to-github-when-i-have-2-factor-authentication-enabled) and read the linked Github documentation please.
